### ISSUE TITLE
Error during Downloading ROM

### ISSUE THREAD

**Issue by wyatt-wong** [mgcaret/rom4x#10]
I got the following error when I run "rake" in the rom4x folder. However I found the iic_rom4x.bin was successfully created.

I am using the following ruby and rake versions:

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
rake, version 13.0.1

========================
Downloading ROM...
/Users/wyattwong/Downloads/rom4x/rom4x/Rakefile:38: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

**Comment by mgcaret** [comment]
I will fix this, but the error can be safely ignored for now.

**Comment by wyatt-wong** [comment]
I see, thanks.
