### ISSUE TITLE
Mockingboard

### ISSUE THREAD

**Issue by synacktic** [mgcaret/rom4x#11]
I have a Mockingboard 4c and to make it function, I often need to do:
CALL-151
*C403:FF FF

This enabled it and clobbers the mouse port. I never use the mouse, and would prefer the Mockingboard just to be enabled at every boot.

Is it possible to patch the 4x rom to do this?

**Comment by mgcaret** [comment]
Oh, I forgot to respond to this.   ROM 4X uses the firmware layout of the memory-expandable IIc, placing the mouse in slot 7 and the memory expansion firmware in slot 4. Enabling the Mockingboard 4c clobbers the memory expansion firmware, which is used during the machine’s boot process.  

While it is possible to modify the ROM to do what you want, I created ROM 4X specifically to enhance the use of a memory expansion card. Disabling the memory expansion firmware basically makes all of the features of ROM 4X useless except for the boot menu.
