### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by godfollower** [mgcaret/rom4x#7]
When running "rake" to patch the ROM4, the following error is thrown and the patches aren't applied:
"ld65: Warning: Option `-o' should precede options `-t' or `-C'"

I manually edited the Rakefile to move "-t none" to the end of the line, and the file compiled without errors and the patches are applied to the stock ROM4.

Environment used: Ubuntu 16.04 tools with the ca65 tool installed through apt after adding the repository to my sources.list..

**Comment by mgcaret** [comment]
Hi,

What is the output of ``ca65 --version`` on your system?

**Comment by mgcaret** [comment]
FYI if you installed the cc65 tools via the http://spiro.trikaliotis.net/debian repository, the versions hosted there are approaching five years old.

**Comment by godfollower** [comment]
Output:
`ld65 V2.13.9 - (C) Copyright 1998-2009, Ullrich von Bassewitz
ld65: Error: No object files to link
`
And yes, I didn't find any indication there was new builds or anymore maintainance on the code so here is the sources.list:
`# 6502 cross assembler:
deb     http://debian.trikaliotis.net/ stable contrib
deb-src http://debian.trikaliotis.net/ stable contrib
`
Is there a newer source for APT?

**Comment by mgcaret** [comment]
I'm sorry, but I'm not a Debian user so I can't say with 100% certainty.

You might try here, though:  https://software.opensuse.org/download.html?project=home%3Astrik&package=cc65  (despite being a link to OpenSUSE, there are Debian builds there).

**Comment by godfollower** [comment]
Changed over to that source, and did the magic and it works with out the error as you delivered. You might want to note a minimum version of CC65 in the doc to make sure they are using the more recent stuff for the tool. For anyone reading this, the version of ld65 on my system that worked without an edit is: V2.16. V2.13.9 is the version that has the issue.

**Comment by mgcaret** [comment]
Docs updated as suggested.  Closing the issue.
